// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ForgetPasswordAuthForgetPasswordPostData, ForgetPasswordAuthForgetPasswordPostErrors, ForgetPasswordAuthForgetPasswordPostResponses, GetSessionAuthSessionGetData, GetSessionAuthSessionGetErrors, GetSessionAuthSessionGetResponses, HealthHealthGetData, HealthHealthGetResponses, ResetPasswordEndpointAuthResetPasswordPostData, ResetPasswordEndpointAuthResetPasswordPostErrors, ResetPasswordEndpointAuthResetPasswordPostResponses, RootGetData, RootGetResponses, SignInAuthSignInPostData, SignInAuthSignInPostErrors, SignInAuthSignInPostResponses, SignOutAuthSignOutPostData, SignOutAuthSignOutPostErrors, SignOutAuthSignOutPostResponses, SignUpAuthSignUpPostData, SignUpAuthSignUpPostErrors, SignUpAuthSignUpPostResponses, VerifyEmailAuthVerifyGetData, VerifyEmailAuthVerifyGetErrors, VerifyEmailAuthVerifyGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Sign Up
 *
 * Register a new user with email + password (credential provider).
 *
 * An email-verification link is sent automatically.
 */
export const signUpAuthSignUpPost = <ThrowOnError extends boolean = false>(options: Options<SignUpAuthSignUpPostData, ThrowOnError>) => (options.client ?? client).post<SignUpAuthSignUpPostResponses, SignUpAuthSignUpPostErrors, ThrowOnError>({
    url: '/auth/sign-up',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign In
 *
 * Authenticate with email + password and receive a session + JWT.
 */
export const signInAuthSignInPost = <ThrowOnError extends boolean = false>(options: Options<SignInAuthSignInPostData, ThrowOnError>) => (options.client ?? client).post<SignInAuthSignInPostResponses, SignInAuthSignInPostErrors, ThrowOnError>({
    url: '/auth/sign-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Session
 *
 * Retrieve current session info and issue a fresh JWT.
 *
 * Used by the frontend on page load or when the JWT expires.
 * This also extends the session expiry.
 */
export const getSessionAuthSessionGet = <ThrowOnError extends boolean = false>(options?: Options<GetSessionAuthSessionGetData, ThrowOnError>) => (options?.client ?? client).get<GetSessionAuthSessionGetResponses, GetSessionAuthSessionGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * Verify Email
 *
 * Verify a user's email address using the token from the verification link.
 */
export const verifyEmailAuthVerifyGet = <ThrowOnError extends boolean = false>(options: Options<VerifyEmailAuthVerifyGetData, ThrowOnError>) => (options.client ?? client).get<VerifyEmailAuthVerifyGetResponses, VerifyEmailAuthVerifyGetErrors, ThrowOnError>({ url: '/auth/verify', ...options });

/**
 * Forget Password
 *
 * Request a password-reset link. Always succeeds to prevent enumeration.
 */
export const forgetPasswordAuthForgetPasswordPost = <ThrowOnError extends boolean = false>(options: Options<ForgetPasswordAuthForgetPasswordPostData, ThrowOnError>) => (options.client ?? client).post<ForgetPasswordAuthForgetPasswordPostResponses, ForgetPasswordAuthForgetPasswordPostErrors, ThrowOnError>({
    url: '/auth/forget-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset Password Endpoint
 *
 * Set a new password using the token from the reset-password email.
 */
export const resetPasswordEndpointAuthResetPasswordPost = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordEndpointAuthResetPasswordPostData, ThrowOnError>) => (options.client ?? client).post<ResetPasswordEndpointAuthResetPasswordPostResponses, ResetPasswordEndpointAuthResetPasswordPostErrors, ThrowOnError>({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign Out
 *
 * Sign out the current user by deleting their session and clearing the cookie.
 */
export const signOutAuthSignOutPost = <ThrowOnError extends boolean = false>(options?: Options<SignOutAuthSignOutPostData, ThrowOnError>) => (options?.client ?? client).post<SignOutAuthSignOutPostResponses, SignOutAuthSignOutPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/sign-out',
    ...options
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
