// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AuthResponse
 */
export type AuthResponse = {
    user: UserResponse;
    session: SessionResponse;
    /**
     * Access Token
     */
    access_token: string;
};

/**
 * ForgetPasswordRequest
 */
export type ForgetPasswordRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Token
     */
    token: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * SignInRequest
 */
export type SignInRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SignUpRequest
 */
export type SignUpRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Image
     */
    image?: string | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Email Verified
     */
    email_verified: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SignUpAuthSignUpPostData = {
    body: SignUpRequest;
    path?: never;
    query?: never;
    url: '/auth/sign-up';
};

export type SignUpAuthSignUpPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignUpAuthSignUpPostError = SignUpAuthSignUpPostErrors[keyof SignUpAuthSignUpPostErrors];

export type SignUpAuthSignUpPostResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type SignUpAuthSignUpPostResponse = SignUpAuthSignUpPostResponses[keyof SignUpAuthSignUpPostResponses];

export type SignInAuthSignInPostData = {
    body: SignInRequest;
    path?: never;
    query?: never;
    url: '/auth/sign-in';
};

export type SignInAuthSignInPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignInAuthSignInPostError = SignInAuthSignInPostErrors[keyof SignInAuthSignInPostErrors];

export type SignInAuthSignInPostResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type SignInAuthSignInPostResponse = SignInAuthSignInPostResponses[keyof SignInAuthSignInPostResponses];

export type GetSessionAuthSessionGetData = {
    body?: never;
    headers?: {
        /**
         * X-Session-Token
         */
        'X-Session-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetSessionAuthSessionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionAuthSessionGetError = GetSessionAuthSessionGetErrors[keyof GetSessionAuthSessionGetErrors];

export type GetSessionAuthSessionGetResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type GetSessionAuthSessionGetResponse = GetSessionAuthSessionGetResponses[keyof GetSessionAuthSessionGetResponses];

export type VerifyEmailAuthVerifyGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/auth/verify';
};

export type VerifyEmailAuthVerifyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyEmailAuthVerifyGetError = VerifyEmailAuthVerifyGetErrors[keyof VerifyEmailAuthVerifyGetErrors];

export type VerifyEmailAuthVerifyGetResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type VerifyEmailAuthVerifyGetResponse = VerifyEmailAuthVerifyGetResponses[keyof VerifyEmailAuthVerifyGetResponses];

export type ForgetPasswordAuthForgetPasswordPostData = {
    body: ForgetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/forget-password';
};

export type ForgetPasswordAuthForgetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForgetPasswordAuthForgetPasswordPostError = ForgetPasswordAuthForgetPasswordPostErrors[keyof ForgetPasswordAuthForgetPasswordPostErrors];

export type ForgetPasswordAuthForgetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ForgetPasswordAuthForgetPasswordPostResponse = ForgetPasswordAuthForgetPasswordPostResponses[keyof ForgetPasswordAuthForgetPasswordPostResponses];

export type ResetPasswordEndpointAuthResetPasswordPostData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordEndpointAuthResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordEndpointAuthResetPasswordPostError = ResetPasswordEndpointAuthResetPasswordPostErrors[keyof ResetPasswordEndpointAuthResetPasswordPostErrors];

export type ResetPasswordEndpointAuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ResetPasswordEndpointAuthResetPasswordPostResponse = ResetPasswordEndpointAuthResetPasswordPostResponses[keyof ResetPasswordEndpointAuthResetPasswordPostResponses];

export type SignOutAuthSignOutPostData = {
    body?: never;
    headers?: {
        /**
         * X-Session-Token
         */
        'X-Session-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type SignOutAuthSignOutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignOutAuthSignOutPostError = SignOutAuthSignOutPostErrors[keyof SignOutAuthSignOutPostErrors];

export type SignOutAuthSignOutPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type SignOutAuthSignOutPostResponse = SignOutAuthSignOutPostResponses[keyof SignOutAuthSignOutPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
